Workarround when author is null
```
+ ./zig-out/bin/github-stats
warning: More than 100 repos returned for 1/2026. Some data may be omitted due to GitHub API limitations.
warning: More than 100 repos returned for 2/2026. Some data may be omitted due to GitHub API limitations.
warning: More than 100 repos returned for 4/2026. Some data may be omitted due to GitHub API limitations.
warning: More than 100 repos returned for 8/2025. Some data may be omitted due to GitHub API limitations.
warning: More than 100 repos returned for 9/2025. Some data may be omitted due to GitHub API limitations.
warning: More than 100 repos returned for 11/2025. Some data may be omitted due to GitHub API limitations.
error: Contributors parse error for ruby/rubygems: error.UnexpectedToken